dataset_path: /path_to_your/lmms-eval-ovbench/lmms_eval/tasks/ovbench_full/ovbench_full
dataset_kwargs:
  token: True
  cache_dir: /path_to_your/lmms-eval-ovbench/lmms_eval/tasks/ovbench_full/ovbench_full
  video: True
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false

output_type: generate_until
doc_to_visual: !function utils.ovbench_doc_to_visual
doc_to_text: !function utils.ovbench_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.ovbench_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: ovbench_accuracy
    aggregation: !function utils.ovbench_aggregate_results
    higher_is_better: true